--GRANT PRIVILEGE IN A TABLE TO USER
GRANT &PRIVILEGENAME ON system.&TABLENAME TO &USERNAME;
--WITH GRANT OPTION
GRANT &PRIVILEGENAME ON system.&TABLENAME TO &USERNAME WITH GRANT OPTION;

--GRANT PRIVILEGES ALL TABLE TO USER
GRANT &PRIVILEGENAME  TO &USERNAME;
--WITH GRANT OPTION
GRANT &PRIVILEGENAME TO &USERNAME WITH GRANT OPTION;

--GRANT PRIVILEGe IN A TABLE TO ROLE
GRANT &PRIVILEGE ON system.&TABLENAME TO &ROLENAME;
--GRANT PRIVILEGe IN ALL TABLE TO ROLE
GRANT &PRIVILEGE TO &ROLENAME;
--GRANT ROLE TO USER
GRANT &ROLENAME TO &USERNAME;

--GRANT UPDATE ON COLUMN TO USER
GRANT &UPDATE(&COLUMNNAME) ON system.&TABLENAME TO &USERNAME;
--GRANT UPDATE ON COLUMN TO USER WITH GRANT OPTION
GRANT &UPDATE(&COLUMNNAME) ON system.&TABLENAME TO &USERNAME WITH GRANT OPTION;

--GRANT SELECT ON COLUMN: IN NEW ORACLE CAN GRANT SELECT PRIVILEGES ON COLUMN. WE USE VIEW
/

connect DBA1;
GRANT SELECT ON system.NHANVIEN TO USER_ROLE;
SELECT * FROM SYSTEM.NHANVIEN;
GRANT &PRIVILEGE ON system.&TABLENAME TO &ROLENAME;

GRANT &PRIVILEGE ON system.&TABLENAME TO &ROLENAME;
connect system;
select * from system.DONVI;
grant SELECT (MAPHONG)on system.DONVI to USER_ROLE;
GRANT SELECT(TENDV) ON system.DONVI TO USER2;
GRANT &SELECT (&COLUMNNAME ) ON system.&TABLENAME TO &USERNAME;
GRANT &SELECT(&COLUMNNAME) ON system.&TABLENAME TO &USERNAME WITH GRANT OPTION;


CONNECT DBA1;
GRANT UPDATE ON SYSTEM.DONVI TO USER1 as DBA_ROLE;
GRANT &UPDATE(&COLUMNNAME) ON system.&TABLENAME TO &USERNAME;
CONNECT USER1;
SELECT * FROM SYSTEM.DONVI;
